config/routes.rb
SmartFlat::Application.routes.draw do
  devise_for :users

  root :to => "devices#list"
  get "devices/list" => "devices#list"
  get "devices/new" => "devices#new"
  get "devices/:id" => "devices#edit"
  get "devices/:id/image" => "devices#image"

  get "providers/list" => "providers#list"
  get "providers/new" => "providers#new"
  get "providers/:id" => "providers#edit"

  get "messages/DATA=:id" => "wiflys#postSensorsData"
  get "messages/list" => "messages#list"

  get "scheduler" => "schedulers#start_scheduler"
  get "schedulers/list" => "schedulers#list"
  get "schedulers/new" => "schedulers#new"
  get "schedulers/:id" => "schedulers#edit"

  get "reports/list" => "reports#list"
  get "reports/:id" => "reports#edit"

  resources :devices, :providers, :schedulers, :reports
end

app/models/meter.rb
class Meter < Device
  has_one :counter, :as => :receiver, :class_name => 'CounterWiFlyProvider'

  # Return start value for counter.
  def diff_value
    custom_value
  end

  # Sets start value for counter.
  def diff_value=(value)
    custom_value = value
  end

  # Return diff plus counter values
  # as full counter value
  def meter_value
    begin
      counter_value_ = counter.get_value
      result = diff_value.to_f + counter_value_.to_f
      result = result.round(3)
      Rails.logger.debug("meter_value=#{result}")
    rescue => exception
      raise IOError, "Provider access error: #{counter.name}"
      result = Status::UNKNOWN
    end
    result
  end

  # Init new meter value
  def meter_value=(value)
    diff_value = meter_value
    begin
      counter.reset
    rescue => exception
      raise IOError, "Provider access error: #{counter.name}"
    end
  end

  # Return meter value ready for display.
  def meter_state
    begin
      result = meter_value
    rescue => exception
      Rails.logger.info("#{exception}")
      result = Status::UNKNOWN
    end
  end

  # Provide meter serial number.
  def meter_sn
    counter.get_sn
  end

  # Hash of meter state.
  def get_hash
    result = super()
    result['counter_value'] = meter_value.to_s
    result['serial_number'] = "#{meter_sn}"
    result
  end

end

app/views/meters/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @device.name %></title>
</head>
<body>
    <h2><%= @device.name %>(<%= @device.id %>):</h2>
    <% if @device.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @device.errors.full_messages.each do |msg| %>
            <li style="color: red;"><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div style="width: 40%">
      <table class="table table-striped">
        <tr>
          <td>SN</td>
          <td><%= @device.meter_sn %></td>
        </tr>
        <tr>
          <td width=100>Initial</td>
          <td>
            <%= form_for(@device, :url => devices_path, :url => {:id => @device.id}) do |f| %>
                <%= f.text_field :custom_value, :size => 10 %>
                <%= f.submit "Change" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Value</td>
          <td><%= @device.meter_state %></td>
        </tr>
      </table>
    </div>
</body>
</html>